# Generated by Django 4.2.16 on 2024-11-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='reeipe_image',
            new_name='receipe_image',
        ),
    ]
